# Site settings
title: George Chapman
author: George Chapman
email: george@gnchapman.info
description: >-
  34-year-old accessibility engineer currently working for an assistive
  technology company based in London. Committed to helping people with
  disabilities. Extensive experience writing software for and delivering
  training to clients for nearly eight years. I also have a background in
  marketing and fine art. In my spare time I paint, write an art
  newsletter and answer accessibility questions on Stack Overflow.
baseurl: "/cv" # the subpath of your site, e.g. /blog
url: "https://ptikobj.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

resume_section_experience:      true
resume_section_education:       true
resume_section_skills:          true
resume_section_interests:       true

# Social media
instagram_username:     gn.chapman
# twitter_username:       gnchapman
github_username:        gnchapman
stackoverflow:          "17077605"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
